/*******************************************************************************
 * SNOWFLAKE VIDEO INTELLIGENCE DEMO - TABLE CREATION
 * 
 * This script creates the tables needed for video analysis:
 * - VIDEO_METADATA: Stores video file information
 * - VIDEO_ANALYSIS_RESULTS: Stores analysis results from Cortex AI
 * - VIDEO_QUERIES: Stores user queries and responses
 * 
 * Prerequisites: Run 01_initial_setup.sql first
 ******************************************************************************/

USE DATABASE VIDEO_INTELLIGENCE_DB;
USE SCHEMA VIDEO_ANALYSIS;
USE WAREHOUSE VIDEO_ANALYSIS_WH;

-- Table to store video metadata
CREATE OR REPLACE HYBRID TABLE VIDEO_METADATA (
    VIDEO_ID VARCHAR(36) DEFAULT UUID_STRING() PRIMARY KEY,
    FILE_NAME VARCHAR(500) NOT NULL,
    FILE_PATH VARCHAR(1000) NOT NULL,
    FILE_SIZE_BYTES NUMBER,
    UPLOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    VIDEO_DURATION_SECONDS NUMBER,
    VIDEO_FORMAT VARCHAR(50),
    VIDEO_RESOLUTION VARCHAR(50),
    PROCESSED BOOLEAN DEFAULT FALSE,
    CREATED_BY VARCHAR(100) DEFAULT CURRENT_USER(),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
) COMMENT = 'Stores metadata about uploaded videos';

-- Table to store video analysis results
CREATE OR REPLACE HYBRID TABLE VIDEO_ANALYSIS_RESULTS (
    ANALYSIS_ID VARCHAR(36) DEFAULT UUID_STRING() PRIMARY KEY,
    VIDEO_ID VARCHAR(36) NOT NULL,
    ANALYSIS_TYPE VARCHAR(100),
    FRAME_NUMBER NUMBER,
    TIMESTAMP_IN_VIDEO NUMBER,
    ANALYSIS_RESULT VARIANT,
    CONFIDENCE_SCORE FLOAT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT FK_VIDEO FOREIGN KEY (VIDEO_ID) REFERENCES VIDEO_METADATA(VIDEO_ID)
) COMMENT = 'Stores detailed analysis results for each video';

-- Table to store user queries and responses
CREATE OR REPLACE HYBRID TABLE VIDEO_QUERIES (
    QUERY_ID VARCHAR(36) DEFAULT UUID_STRING() PRIMARY KEY,
    VIDEO_ID VARCHAR(36) NOT NULL,
    QUESTION TEXT NOT NULL,
    ANSWER TEXT,
    CONTEXT VARIANT,
    MODEL_USED VARCHAR(100),
    RESPONSE_TIME_MS NUMBER,
    CREATED_BY VARCHAR(100) DEFAULT CURRENT_USER(),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT FK_VIDEO_QUERY FOREIGN KEY (VIDEO_ID) REFERENCES VIDEO_METADATA(VIDEO_ID)
) COMMENT = 'Stores user questions and AI-generated answers about videos';

-- Display success message
SELECT 'Tables created successfully!' AS STATUS;
SELECT 'VIDEO_METADATA' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM VIDEO_METADATA
UNION ALL
SELECT 'VIDEO_ANALYSIS_RESULTS', COUNT(*) FROM VIDEO_ANALYSIS_RESULTS
UNION ALL
SELECT 'VIDEO_QUERIES', COUNT(*) FROM VIDEO_QUERIES;

